Resources:
  Appointments:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_TABLE}
      AttributeDefinitions:
        - AttributeName: insuredId
          AttributeType: S
        - AttributeName: scheduleId
          AttributeType: N
      KeySchema:
        - AttributeName: insuredId
          KeyType: HASH
        - AttributeName: scheduleId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST