# API Gateway environment
environments:
  DESA: desa
  TEST: test
  PROD: prod

environmentsTags:
  DESA: DEV
  TEST: TEST
  PROD: PROD

# Regions code and abbreviation
# Validar/usar regiones válidas de acuerdo a la cuenta (por default está con Control Tower)
regions:
  code:
    DESA: us-east-2
    TEST: us-east-2
    PROD: us-east-1
  abrev:
    DESA: UE2
    TEST: UE2
    PROD: UE1

# Accounts
# Validar/usar ids de las cuentas que se usarán (por default está con Control Tower)
accounts:
  id:
    DESA: 000000000000
    TEST: 000000000000
    PROD: 000000000000
  abrev:
    DESA: LMB
    TEST: LMB
    PROD: LMB

# Deployment bucket
# Colocar nombre de buckets creados por el arquitecto específicamente para el proyecto
deploymentBucket:
  DESA: bucketdesa
  TEST: buckettest
  PROD: bucketprod

# Lambda's role
# Colocar el nombre de los roles creados por el arquitecto específicamente para cada lambda o para el repositorio
role:
  DESA: arn:aws:iam::${self:custom.accountId}:role/serverless-execution-role
  TEST: arn:aws:iam::${self:custom.accountId}:role/serverless-execution-role
  PROD: arn:aws:iam::${self:custom.accountId}:role/serverless-execution-role

# VPCs (Para APIs Canal por le general no se requiere y se puede eliminar)
vpc:
  DESA:
    securityGroupIds:
      - sg-0223cbd12ea7afdd8
    subnetIds:
      - subnet-03f752eb99013ffb9
      - subnet-052f42bc03b315afc
      - subnet-05297d3055e235231
  TEST:
    securityGroupIds:
      - sg-xxxxxxxxxxxxxxxxxxxx
    subnetIds:
      - subnet-xxxxxxxxxxxxxxxxx
      - subnet-xxxxxxxxxxxxxxxxx
      - subnet-xxxxxxxxxxxxxxxxx
  PROD:
    securityGroupIds:
      - xx-xxxxxxxxxxxxxxxxxxxx
    subnetIds:
      - subnet-xxxxxxxxxxxxxxxxx
      - subnet-xxxxxxxxxxxxxxxxx
      - subnet-xxxxxxxxxxxxxxxxx

# Abreviación de repositorio usado en nombre de recursos
repoAbrev: RETOINDRA

# X-API-Key para el API Gateway
xapiKey:
  DESA: A9vX7PmKqD25o8NgnUOYZrQWLMve6Cblo4JTFsC3
  TEST: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  PROD: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

snsTopicCountry:
  DESA: arn:aws:sns:us-east-2:829357759972:SNSCOUNTRY01
  TEST: arn:aws:sns:us-east-2:000000000000:topictest
  PROD: arn:aws:sns:us-east-1:000000000000:topicprod